const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,f=[]){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let players=store.get('hl_players'), recent=store.get('hl_recent');
const titles={home:'Dashboard',rules:'Rule Finder',comp:'Compensation Calculator',punishment:'Punishment Guide',players:'Player Records',appeals:'Appeal Review'};
function openPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=titles[id];$('.sidebar').classList.remove('open');if(id==='home')renderHomeStats()}
$$('[data-page]').forEach(b=>b.onclick=()=>openPage(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>openPage(b.dataset.open));$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#date').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date());
function addRecent(text,type){recent=[{text,type,at:Date.now()},...recent.filter(x=>x.text!==text)].slice(0,8);store.set('hl_recent',recent);renderRecent()}
function renderRecent(){const el=$('#recentList');if(!recent.length){el.className='empty compact';el.textContent='Your recent searches and records will appear here.';return}el.className='';el.innerHTML=recent.slice(0,4).map(x=>`<div class="historyitem"><b>${esc(x.text)}</b><small>${esc(x.type)} · ${timeAgo(x.at)}</small></div>`).join('')}
function renderHomeStats(){let cases=players.reduce((n,p)=>n+(p.history?.length||0),0),appeals=players.reduce((n,p)=>n+(p.appeals?.length||0),0);$('#homePlayers').textContent=players.length;$('#homeCases').textContent=cases;$('#homeAppeals').textContent=appeals}
$('#clearRecent').onclick=()=>{recent=[];store.set('hl_recent',recent);renderRecent()};renderRecent();renderHomeStats();
function timeAgo(t){let m=Math.max(0,Math.round((Date.now()-t)/60000));if(m<1)return'just now';if(m<60)return`${m}m ago`;let h=Math.round(m/60);return h<24?`${h}h ago`:`${Math.round(h/24)}d ago`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(s){if(!s)return'—';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00'))}
function safeLink(url,label){if(!url)return'';return `<a class="inline-link" href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)} ↗</a>`}

const demoRules=[
 {name:'Metagaming',keywords:['meta','metagaming','stream','ooc','out of character','information','knowledge'],hint:'Using out-of-character knowledge to gain an in-character advantage.'},
 {name:'Combat Logging',keywords:['combat log','disconnect','left server','leave server','arrest','danger'],hint:'Leaving the server to avoid or improperly end an active situation.'},
 {name:'RDM / VDM',keywords:['rdm','vdm','random deathmatch','vehicle deathmatch','randomly shot','ran over'],hint:'Potential random or unjustified player/vehicle attack.'},
 {name:'Powergaming',keywords:['powergame','powergaming','unrealistic','force action'],hint:'Potential unrealistic or forced roleplay behaviour.'}
];
$$('[data-rule-tab]').forEach(b=>b.onclick=()=>{$$('[data-rule-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#keywordBox').hidden=b.dataset.ruleTab!=='keywords';$('#situationBox').hidden=b.dataset.ruleTab!=='situation'});
function searchRules(q){q=q.trim().toLowerCase();if(!q)return;let words=q.split(/\s+/);let scored=demoRules.map(r=>({...r,score:r.keywords.reduce((n,k)=>n+(q.includes(k)||k.includes(q)||words.some(w=>w.length>3&&k.includes(w))?1:0),0)+(q.includes(r.name.toLowerCase())?3:0)})).filter(r=>r.score).sort((a,b)=>b.score-a.score);let el=$('#ruleResults');el.innerHTML=scored.length?scored.map((r,i)=>`<div class="result" data-rule="${esc(r.name)}"><b>${i?'Possible match':'Most relevant'} · ${esc(r.name)}</b><small>${esc(r.hint)}</small></div>`).join(''):`<div class="empty">No prototype match. The production search will query the full official rules dataset.</div>`;$$('[data-rule]').forEach(x=>x.onclick=()=>showRule(x.dataset.rule));addRecent(q,'Rule search')}
function showRule(name){let r=demoRules.find(x=>x.name===name);$('#ruleDetail').innerHTML=`<p class="eyebrow">RULE MATCH</p><h2>${esc(r.name)}</h2><p style="color:#9ba8b8;line-height:1.6">${esc(r.hint)}</p><div class="notice" style="margin-top:20px">↗ <span>The backend will sync the current official Highlife wording and source link here.</span></div><div class="guidance"><span>🔒</span><div><strong>Private punishment guidance</strong><p>Recommendations, escalation logic and precedent will be fetched after authentication — never from this GitHub bundle.</p></div></div><button class="secondary full" onclick="document.querySelector('#caseRule').value='${esc(r.name)}';document.querySelector('[data-page=punishment]').click()">Use in punishment review</button>`}
$('#ruleSearch').onclick=()=>searchRules($('#ruleQuery').value);$('#situationSearch').onclick=()=>searchRules($('#situationQuery').value);$('#ruleQuery').onkeydown=e=>{if(e.key==='Enter')searchRules(e.target.value)};

function addCompRow(){let d=document.createElement('div');d.className='comp-row';d.innerHTML='<label>Item<input placeholder="Search item..."/></label><label>Quantity<input type="number" min="1" value="1"/></label><button title="Remove">×</button>';d.querySelector('button').onclick=()=>d.remove();$('#compRows').append(d)}
$('#addComp').onclick=addCompRow;$('#clearComp').onclick=()=>{$('#compRows').innerHTML='';$('#cashLost').value=0;addCompRow()};addCompRow();
$('#copyComp').onclick=async()=>{try{await navigator.clipboard.writeText($('#compMessage').textContent);$('#copyComp').textContent='Copied';setTimeout(()=>$('#copyComp').textContent='Copy message',1200)}catch{}};

function addBan(data={}){let d=document.createElement('div');d.className='ban-row';d.innerHTML=`<label>Reason<input class="breason" value="${esc(data.reason||'')}" placeholder="Reason"/></label><label>Start<input class="bstart" type="date" value="${esc(data.start||'')}"/></label><label>End<input class="bend" type="date" value="${esc(data.end||'')}"/></label><div class="duration">—</div><button title="Remove">×</button>`;d.querySelectorAll('input').forEach(i=>i.oninput=calcBans);d.querySelector('button').onclick=()=>{d.remove();calcBans()};$('#banRows').append(d);calcBans()}
function getBans(){return $$('.ban-row').map(r=>({reason:r.querySelector('.breason').value.trim(),start:r.querySelector('.bstart').value,end:r.querySelector('.bend').value})).filter(x=>x.start||x.end||x.reason)}
function daysBetween(a,b){if(!a||!b)return 0;return Math.max(0,Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000))}
function calcCurrent(){let d=daysBetween($('#currentStart').value,$('#currentEnd').value);$('#currentLength').textContent=d?`${d} days`:'—'}
$('#currentStart').oninput=calcCurrent;$('#currentEnd').oninput=calcCurrent;
function calcBans(){let bans=getBans(),ds=[];$$('.ban-row').forEach(r=>{let d=daysBetween(r.querySelector('.bstart').value,r.querySelector('.bend').value);r.querySelector('.duration').textContent=d?`${d} days`:'—';if(d)ds.push(d)});$('#statBans').textContent=bans.length;$('#statDays').textContent=ds.reduce((a,b)=>a+b,0);$('#statLongest').textContent=`${Math.max(0,...ds)} days`;let ends=bans.map(x=>x.end).filter(Boolean).sort();if(ends.length){let diff=Math.max(0,Math.floor((Date.now()-new Date(ends.at(-1)+'T12:00:00'))/86400000));$('#statLast').textContent=diff===0?'today':`${diff} days ago`;$('#stat90').textContent=ends.filter(x=>(Date.now()-new Date(x+'T12:00:00'))/86400000<=90).length}else{$('#statLast').textContent='—';$('#stat90').textContent='0'}let rule=$('#caseRule').value.trim().toLowerCase();$('#statSame').textContent=rule?bans.filter(x=>x.reason.toLowerCase().includes(rule)||rule.includes(x.reason.toLowerCase())).length:0}
$('#caseRule').oninput=calcBans;$('#addBan').onclick=()=>addBan();addBan();
function clearCase(){['caseProfile','caseRule','caseLink','caseEvidence','caseNotes','currentStart','currentEnd'].forEach(id=>$('#'+id).value='');$('#banRows').innerHTML='';addBan();calcCurrent();calcBans()}
$('#clearCase').onclick=clearCase;

function renderPlayers(filter=''){let q=filter.toLowerCase();let list=players.filter(p=>!q||p.name.toLowerCase().includes(q)||p.profile.toLowerCase().includes(q)||(p.aliases||'').toLowerCase().includes(q));$('#playerList').innerHTML=list.length?list.map(p=>`<div class="playercard" data-player="${p.id}"><b>${esc(p.name)}</b><small>${esc(p.profile)}</small><small>${(p.history||[]).length} case(s) · ${(p.appeals||[]).length} appeal(s)</small></div>`).join(''):'<div class="empty">No player records yet.</div>';$$('[data-player]').forEach(x=>x.onclick=()=>showPlayer(x.dataset.player));renderHomeStats()}
function historyCard(h,i){let len=daysBetween(h.currentStart,h.currentEnd);return `<div class="casecard"><div class="casehead"><div><b>${esc(h.rule||'Punishment')}</b><small>${h.created?new Date(h.created).toLocaleDateString('en-GB'):'Saved case'}</small></div><span>${len?len+' days':'No length'}</span></div><p>${esc(h.notes||'No incident notes.')}</p><div class="linkrow">${safeLink(h.caseLink,'Case / ticket')}${(h.evidence||[]).map((u,j)=>safeLink(u,'Evidence '+(j+1))).join('')}</div><small class="mutedline">Ban: ${fmtDate(h.currentStart)} → ${fmtDate(h.currentEnd)} · ${h.bans?.length||0} prior(s) recorded at review</small></div>`}
function showPlayer(id){let p=players.find(x=>x.id===id);if(!p)return;addRecent(p.name,'Player record');let hist=(p.history||[]).map(historyCard).join('')||'<div class="empty compact">No punishment history saved yet.</div>';let appeals=(p.appeals||[]).map(a=>`<div class="historyitem"><b>${esc(a.outcome||'Appeal review')}</b><small>${esc(a.notes||'No notes')} · ${new Date(a.created).toLocaleDateString('en-GB')}</small>${safeLink(a.link,'Appeal link')}</div>`).join('')||'<div class="empty compact">No appeal reviews saved yet.</div>';$('#playerDetail').innerHTML=`<p class="eyebrow">PLAYER RECORD</p><div class="recordtop"><div><h2>${esc(p.name)}</h2>${p.aliases?`<small class="mutedline">Previous names: ${esc(p.aliases)}</small>`:''}</div><a class="external" href="${esc(p.profile)}" target="_blank" rel="noreferrer">Open profile ↗</a></div><p class="recordnotes">${esc(p.notes||'No private notes added.')}</p><div class="recordactions"><button class="secondary" data-start-case="${p.id}">♢ New case</button><button class="secondary" data-start-appeal="${p.id}">↺ Review appeal</button></div><div class="panelhead section-gap"><h3>Punishment history</h3><span>${(p.history||[]).length} records</span></div>${hist}<div class="panelhead section-gap"><h3>Appeal history</h3><span>${(p.appeals||[]).length} reviews</span></div>${appeals}`;$$('[data-start-case]').forEach(b=>b.onclick=()=>startCaseForPlayer(b.dataset.startCase));$$('[data-start-appeal]').forEach(b=>b.onclick=()=>startAppealForPlayer(b.dataset.startAppeal))}
function startCaseForPlayer(id){let p=players.find(x=>x.id===id);if(!p)return;clearCase();$('#caseProfile').value=p.profile;(p.history||[]).forEach(h=>{let reason=h.rule||'',start=h.currentStart,end=h.currentEnd;if(reason||start||end)addBan({reason,start,end})});openPage('punishment')}
function startAppealForPlayer(id){openPage('appeals');showAppealPlayer(id)}
$('#newPlayer').onclick=()=>$('#playerDialog').showModal();$('#quickNewPlayer').onclick=()=>$('#playerDialog').showModal();$('#playerSearchBtn').onclick=()=>renderPlayers($('#playerSearch').value);$('#playerSearch').oninput=e=>renderPlayers(e.target.value);
$('#playerForm').addEventListener('submit',e=>{if(e.submitter?.id!=='savePlayer')return;e.preventDefault();let name=$('#playerName').value.trim(),profile=$('#playerProfile').value.trim();if(!name||!profile)return;players.unshift({id:crypto.randomUUID(),name,profile,aliases:$('#playerAliases').value.trim(),notes:$('#playerNotes').value.trim(),history:[],appeals:[]});store.set('hl_players',players);renderPlayers();$('#playerForm').reset();$('#playerDialog').close();addRecent(name,'New player')});
$('#saveToPlayer').onclick=()=>{let profile=$('#caseProfile').value.trim();if(!profile){alert('Paste the player profile URL first.');return}let p=players.find(x=>x.profile===profile);if(!p){let name=prompt('No saved player uses that profile yet. Enter their current name:');if(!name)return;p={id:crypto.randomUUID(),name,profile,aliases:'',notes:'',history:[],appeals:[]};players.unshift(p)}let evidence=$('#caseEvidence').value.split('\n').map(x=>x.trim()).filter(Boolean);p.history=p.history||[];p.history.unshift({id:crypto.randomUUID(),rule:$('#caseRule').value.trim(),caseLink:$('#caseLink').value.trim(),evidence,notes:$('#caseNotes').value.trim(),currentStart:$('#currentStart').value,currentEnd:$('#currentEnd').value,bans:getBans(),created:Date.now()});store.set('hl_players',players);renderPlayers();addRecent(p.name,'Punishment record');alert('Saved to this device for prototype testing. Do not rely on this as the permanent confidential database yet.')};

function renderAppealSearch(q=''){q=q.toLowerCase();let list=players.filter(p=>!q||p.name.toLowerCase().includes(q)||p.profile.toLowerCase().includes(q)||(p.aliases||'').toLowerCase().includes(q));$('#appealPlayerResults').innerHTML=list.length?list.map(p=>`<div class="playercard" data-appeal-player="${p.id}"><b>${esc(p.name)}</b><small>${(p.history||[]).length} punishment(s) available</small></div>`).join(''):'<div class="empty compact">No saved player matches that search.</div>';$$('[data-appeal-player]').forEach(b=>b.onclick=()=>showAppealPlayer(b.dataset.appealPlayer))}
function showAppealPlayer(id){let p=players.find(x=>x.id===id);if(!p)return;let options=(p.history||[]).map((h,i)=>`<option value="${i}">${esc(h.rule||'Punishment')} — ${fmtDate(h.currentStart)} (${daysBetween(h.currentStart,h.currentEnd)||'?'} days)</option>`).join('');$('#appealWorkspace').innerHTML=`<div class="recordtop"><div><p class="eyebrow">APPEALING PLAYER</p><h2>${esc(p.name)}</h2></div>${safeLink(p.profile,'Player profile')}</div>${p.aliases?`<p class="mutedline">Previous names: ${esc(p.aliases)}</p>`:''}<label>Punishment being appealed<select id="appealCase">${options||'<option value="">No saved punishments</option>'}</select></label><div id="appealCaseSummary"></div><label>Appeal / ticket link<input id="appealLink" type="url" placeholder="Paste appeal link..."/></label><label>Outcome<select id="appealOutcome"><option>Pending review</option><option>Upheld</option><option>Reduced</option><option>Removed / overturned</option><option>Other</option></select></label><label>Review notes<textarea id="appealNotes" placeholder="Why you reached the decision, useful context, anything to remember later..."></textarea></label><button class="primary full" id="saveAppeal">Save appeal review</button>`;let select=$('#appealCase');function updateSummary(){let h=(p.history||[])[Number(select.value)];if(!h){$('#appealCaseSummary').innerHTML='<div class="empty compact">No punishment record is available for this player yet.</div>';return}$('#appealCaseSummary').innerHTML=`<div class="appeal-summary"><div><small>Offence</small><b>${esc(h.rule||'—')}</b></div><div><small>Ban length</small><b>${daysBetween(h.currentStart,h.currentEnd)||'—'} days</b></div><div><small>Ban dates</small><b>${fmtDate(h.currentStart)} → ${fmtDate(h.currentEnd)}</b></div><div><small>Priors recorded</small><b>${h.bans?.length||0}</b></div></div><p class="recordnotes">${esc(h.notes||'No incident notes saved.')}</p><div class="linkrow">${safeLink(h.caseLink,'Original case')}${(h.evidence||[]).map((u,j)=>safeLink(u,'Evidence '+(j+1))).join('')}</div>`}select.onchange=updateSummary;updateSummary();$('#saveAppeal').onclick=()=>{p.appeals=p.appeals||[];let h=(p.history||[])[Number(select.value)];p.appeals.unshift({id:crypto.randomUUID(),caseId:h?.id||null,link:$('#appealLink').value.trim(),outcome:$('#appealOutcome').value,notes:$('#appealNotes').value.trim(),created:Date.now()});store.set('hl_players',players);renderPlayers();renderHomeStats();addRecent(p.name,'Appeal review');alert('Appeal review saved to this device for prototype testing.')}}
$('#appealSearchBtn').onclick=()=>renderAppealSearch($('#appealPlayerSearch').value);$('#appealPlayerSearch').oninput=e=>renderAppealSearch(e.target.value);renderAppealSearch();renderPlayers();
