(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], api=window.HighlifeAPI;if(!api)return;
let catalog=[];
const money=n=>'$'+Number(n||0).toLocaleString('en-US');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function injectImport(){const intro=$('#comp .sectionintro');if(!intro||$('#compImportBtn'))return;const wrap=intro.querySelector('button')?.parentElement||intro;const b=document.createElement('button');b.id='compImportBtn';b.className='secondary';b.textContent='Import price data';b.style.marginLeft='8px';const input=document.createElement('input');input.type='file';input.accept='.csv,text/csv';input.hidden=true;input.id='compImportFile';intro.append(b,input);b.onclick=()=>input.click();input.onchange=importCsv;}
async function loadCatalog(){try{const d=await api.request('/compensation/items');catalog=d.items||[];renderRows();const note=$('#comp .notice span');if(note)note.innerHTML=catalog.length?`<strong>Private data connected:</strong> ${catalog.length} compensation items are loaded from D1. Prices never appear in the public GitHub code.`:`<strong>No price data loaded yet.</strong> Import the confidential price file once to activate the calculator.`;}catch(e){console.error(e)}}
function rowTemplate(itemId='',qty=1){const d=document.createElement('div');d.className='comp-row private-comp-row';d.innerHTML=`<label>Item<input class="compItem" list="compCatalog" placeholder="Search item..." autocomplete="off"></label><label>Quantity<input class="compQty" type="number" min="1" value="${qty}"></label><div class="compUnit"><small>Unit</small><b>—</b></div><div class="compSub"><small>Total</small><b>—</b></div><button title="Remove">×</button>`;const item=catalog.find(x=>x.id===itemId);if(item)d.querySelector('.compItem').value=item.item_name;d.querySelector('button').onclick=()=>{d.remove();calculate()};d.querySelectorAll('input').forEach(i=>i.addEventListener('input',calculate));return d;}
function ensureDatalist(){let dl=$('#compCatalog');if(!dl){dl=document.createElement('datalist');dl.id='compCatalog';document.body.append(dl)}dl.innerHTML=catalog.map(i=>`<option value="${esc(i.item_name)}"></option>`).join('')}
function renderRows(){ensureDatalist();const box=$('#compRows');if(!box)return;if(!box.querySelector('.private-comp-row')){box.innerHTML='';box.append(rowTemplate())}$('#addComp').onclick=()=>box.append(rowTemplate());$('#clearComp').onclick=()=>{box.innerHTML='';box.append(rowTemplate());$('#cashLost').value=0;calculate()};$('#cashLost').oninput=calculate;calculate()}
function selectedRows(){return $$('.private-comp-row').map(r=>{const name=r.querySelector('.compItem').value.trim(),item=catalog.find(x=>x.item_name===name),quantity=Math.max(1,Number(r.querySelector('.compQty').value||1));return item?{id:item.id,quantity,row:r,name}:null}).filter(Boolean)}
async function calculate(){const rows=selectedRows(),cash=Math.max(0,Number($('#cashLost').value||0));$$('.private-comp-row').forEach(r=>{r.querySelector('.compUnit b').textContent='—';r.querySelector('.compSub b').textContent='—'});if(!rows.length&&!cash){$('#compTotal').textContent='$0';$('#compMessage').textContent='Add an item or cash loss to calculate compensation.';return}try{const d=await api.request('/compensation/calculate',{method:'POST',body:JSON.stringify({cash_lost:cash,items:rows.map(x=>({id:x.id,quantity:x.quantity}))})});(d.lines||[]).forEach(line=>{const hit=rows.find(x=>x.name===line.item_name&&!x.done);if(hit){hit.done=true;hit.row.querySelector('.compUnit b').textContent=money(line.unit_value);hit.row.querySelector('.compSub b').textContent=money(line.subtotal)}});$('#compTotal').textContent=money(d.total);const msg=[];(d.lines||[]).forEach(x=>msg.push(`${x.quantity} ${x.item_name}`));if(cash>0)msg.push(`${money(cash)} Cash`);msg.push(`Total Value: ${money(d.total)}`);$('#compMessage').textContent=msg.join('\n')}catch(e){$('#compTotal').textContent='Error';$('#compMessage').textContent='Could not calculate: '+e.message}}
function parseCsv(text){const out=[];for(const raw of text.replace(/^\uFEFF/,'').split(/\r?\n/)){if(!raw.trim())continue;let cells=[],cur='',quote=false;for(let i=0;i<raw.length;i++){const ch=raw[i];if(ch==='"'){if(quote&&raw[i+1]==='"'){cur+='"';i++}else quote=!quote}else if(ch===','&&!quote){cells.push(cur);cur=''}else cur+=ch}cells.push(cur);out.push(cells)}return out}
async function importCsv(e){const file=e.target.files?.[0];if(!file)return;try{const rows=parseCsv(await file.text());const head=rows.shift().map(x=>x.trim().toLowerCase()),ni=head.indexOf('item_name'),vi=head.indexOf('unit_value');if(ni<0||vi<0)throw new Error('CSV must contain item_name and unit_value columns.');const items=rows.map(r=>({item_name:(r[ni]||'').trim(),unit_value:Number(r[vi])})).filter(x=>x.item_name&&Number.isFinite(x.unit_value));if(!items.length)throw new Error('No valid item rows found.');if(!confirm(`Import ${items.length} compensation items into the private database? This replaces the existing price list.`))return;const d=await api.request('/admin/compensation/import',{method:'POST',body:JSON.stringify({items})});alert(`Imported ${d.imported} compensation items privately.`);await loadCatalog()}catch(err){alert('Could not import price data: '+err.message)}finally{e.target.value=''}}
$('#copyComp').onclick=async()=>{try{await navigator.clipboard.writeText($('#compMessage').textContent);$('#copyComp').textContent='Copied';setTimeout(()=>$('#copyComp').textContent='Copy message',1200)}catch{}};
function bind(){injectImport();loadCatalog()}
window.addEventListener('highlife-authenticated',bind);if(api.token)bind();
})();