// Private D1-backed records layer. Loaded after app-core.js so it replaces prototype localStorage handlers.
(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=window.HighlifeAPI;
if(!api)return;
let players=[], details=new Map();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=s=>s?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00')):'—';
const days=(a,b)=>a&&b?Math.max(0,Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)):0;
const link=(u,l)=>u?`<a class="inline-link" href="${esc(u)}" target="_blank" rel="noreferrer">${esc(l)} ↗</a>`:'';
const aliases=p=>{try{return JSON.parse(p.previous_names||'[]')}catch{return[]}};
async function loadPlayers(q=''){
 try{const d=await api.request('/players'+(q?`?q=${encodeURIComponent(q)}`:''));players=d.players||[];renderPlayers();renderAppeal();stats();}
 catch(e){$('#playerList').innerHTML=`<div class="empty">Could not load private records: ${esc(e.message)}</div>`;}
}
function stats(){const pc=players.length, cc=players.reduce((n,p)=>n+Number(p.case_count||0),0);$('#homePlayers').textContent=pc;$('#homeCases').textContent=cc;$('#homeAppeals').textContent='—';}
function renderPlayers(){const el=$('#playerList');el.innerHTML=players.length?players.map(p=>`<div class="playercard" data-d1-player="${p.id}"><b>${esc(p.current_name)}</b><small>${esc(p.profile_url)}</small><small>${Number(p.case_count||0)} case(s)</small></div>`).join(''):'<div class="empty">No player records yet.</div>';$$('[data-d1-player]').forEach(x=>x.onclick=()=>showPlayer(x.dataset.d1Player));}
async function getDetail(id){const d=await api.request(`/players/${encodeURIComponent(id)}`);details.set(id,d);return d;}
async function showPlayer(id){try{const d=await getDetail(id),p=d.player,als=aliases(p);const hist=(d.cases||[]).map(c=>`<div class="casecard"><div class="casehead"><div><b>${esc(c.rule_name||'Punishment')}</b><small>${c.created_at?new Date(c.created_at+'Z').toLocaleDateString('en-GB'):'Saved case'}</small></div><span>${c.duration_days?c.duration_days+' days':'No length'}</span></div><p>${esc(c.incident_notes||'No incident notes.')}</p><div class="linkrow">${link(c.ticket_url,'Case / ticket')}${link(c.evidence_url,'Evidence')}</div><small class="mutedline">Ban: ${fmt(c.ban_start)} → ${fmt(c.ban_end)} · ${(c.prior_bans||[]).length} prior(s) recorded at review</small></div>`).join('')||'<div class="empty compact">No punishment history saved yet.</div>';const aps=(d.appeals||[]).map(a=>`<div class="historyitem"><b>${esc(a.outcome||'Appeal review')}</b><small>${esc(a.notes||'No notes')} · ${a.created_at?new Date(a.created_at+'Z').toLocaleDateString('en-GB'):''}</small>${link(a.appeal_url,'Appeal link')}</div>`).join('')||'<div class="empty compact">No appeal reviews saved yet.</div>';$('#playerDetail').innerHTML=`<p class="eyebrow">PLAYER RECORD</p><div class="recordtop"><div><h2>${esc(p.current_name)}</h2>${als.length?`<small class="mutedline">Previous names: ${esc(als.join(', '))}</small>`:''}</div><a class="external" href="${esc(p.profile_url)}" target="_blank" rel="noreferrer">Open profile ↗</a></div><p class="recordnotes">${esc(p.notes||'No private notes added.')}</p><div class="recordactions"><button class="secondary" id="d1NewCase">♢ New case</button><button class="secondary" id="d1Appeal">↺ Review appeal</button></div><div class="panelhead section-gap"><h3>Punishment history</h3><span>${d.cases.length} records</span></div>${hist}<div class="panelhead section-gap"><h3>Appeal history</h3><span>${d.appeals.length} reviews</span></div>${aps}`;$('#d1NewCase').onclick=()=>startCase(d);$('#d1Appeal').onclick=()=>{document.querySelector('[data-page="appeals"]').click();showAppeal(d)};}catch(e){$('#playerDetail').innerHTML=`<div class="empty">Could not load record: ${esc(e.message)}</div>`;}}
function startCase(d){document.querySelector('[data-page="punishment"]').click();$('#clearCase').click();$('#caseProfile').value=d.player.profile_url;$('#banRows').innerHTML='';(d.cases||[]).forEach(c=>addPrior(c.rule_name,c.ban_start,c.ban_end));if(!d.cases.length)document.querySelector('#addBan').click();}
function addPrior(reason,start,end){const d=document.createElement('div');d.className='ban-row';d.innerHTML=`<label>Reason<input class="breason" value="${esc(reason||'')}" placeholder="Reason"/></label><label>Start<input class="bstart" type="date" value="${esc(start||'')}"/></label><label>End<input class="bend" type="date" value="${esc(end||'')}"/></label><div class="duration">${days(start,end)?days(start,end)+' days':'—'}</div><button title="Remove">×</button>`;d.querySelector('button').onclick=()=>d.remove();$('#banRows').append(d);}
function renderAppeal(){const q=($('#appealPlayerSearch').value||'').toLowerCase(), list=players.filter(p=>!q||p.current_name.toLowerCase().includes(q)||p.profile_url.toLowerCase().includes(q));$('#appealPlayerResults').innerHTML=list.length?list.map(p=>`<div class="playercard" data-d1-appeal="${p.id}"><b>${esc(p.current_name)}</b><small>${Number(p.case_count||0)} punishment(s) available</small></div>`).join(''):'<div class="empty compact">No saved player matches that search.</div>';$$('[data-d1-appeal]').forEach(x=>x.onclick=async()=>showAppeal(await getDetail(x.dataset.d1Appeal)));}
function showAppeal(d){const p=d.player, cases=d.cases||[];$('#appealWorkspace').innerHTML=`<div class="recordtop"><div><p class="eyebrow">APPEALING PLAYER</p><h2>${esc(p.current_name)}</h2></div>${link(p.profile_url,'Player profile')}</div><label>Punishment being appealed<select id="d1AppealCase"><option value="">General / not linked</option>${cases.map(c=>`<option value="${c.id}">${esc(c.rule_name)} — ${fmt(c.ban_start)} (${c.duration_days||'?'} days)</option>`).join('')}</select></label><label>Appeal / ticket link<input id="d1AppealLink" type="url" placeholder="Paste appeal link..."/></label><label>Review notes<textarea id="d1AppealNotes" placeholder="Reasoning, relevant history, notes..."></textarea></label><label>Outcome<select id="d1AppealOutcome"><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="reduced">Reduced</option><option value="denied">Denied</option></select></label><button class="primary full" id="d1SaveAppeal">Save appeal review</button>`;$('#d1SaveAppeal').onclick=async()=>{try{await api.request('/appeals',{method:'POST',body:JSON.stringify({player_id:p.id,case_id:$('#d1AppealCase').value||null,appeal_url:$('#d1AppealLink').value.trim()||null,notes:$('#d1AppealNotes').value.trim(),outcome:$('#d1AppealOutcome').value})});alert('Appeal review saved privately.');await loadPlayers();showAppeal(await getDetail(p.id));}catch(e){alert('Could not save appeal: '+e.message)}};}
function priorRows(){return $$('.ban-row').map(r=>({reason:r.querySelector('.breason')?.value.trim()||'',ban_start:r.querySelector('.bstart')?.value||null,ban_end:r.querySelector('.bend')?.value||null})).filter(x=>x.reason||x.ban_start||x.ban_end);}
async function saveCase(){try{const profile=$('#caseProfile').value.trim();if(!profile)return alert('Paste the player profile URL first.');let p=players.find(x=>x.profile_url===profile);if(!p){const name=prompt('No saved player uses that profile yet. Enter their current name:');if(!name)return;const made=await api.request('/players',{method:'POST',body:JSON.stringify({current_name:name,profile_url:profile,previous_names:[],notes:''})});p={id:made.id,current_name:name,profile_url:profile};}const ev=$('#caseEvidence').value.split('\n').map(x=>x.trim()).filter(Boolean);await api.request('/cases',{method:'POST',body:JSON.stringify({player_id:p.id,rule_name:$('#caseRule').value.trim()||'Unspecified',incident_notes:$('#caseNotes').value.trim(),ban_start:$('#currentStart').value||null,ban_end:$('#currentEnd').value||null,evidence_url:ev.join('\n')||null,ticket_url:$('#caseLink').value.trim()||null,prior_bans:priorRows()})});alert('Case saved privately to D1.');await loadPlayers();}catch(e){alert('Could not save case: '+e.message)}}
function bind(){
 $('#playerSearchBtn').onclick=()=>loadPlayers($('#playerSearch').value.trim());$('#playerSearch').oninput=e=>loadPlayers(e.target.value.trim());
 $('#appealSearchBtn').onclick=()=>loadPlayers($('#appealPlayerSearch').value.trim());$('#appealPlayerSearch').oninput=()=>renderAppeal();
 $('#saveToPlayer').onclick=saveCase;
 $('#playerForm').onsubmit=async e=>{if(e.submitter?.id!=='savePlayer')return;e.preventDefault();try{const name=$('#playerName').value.trim(),profile=$('#playerProfile').value.trim();if(!name||!profile)return;await api.request('/players',{method:'POST',body:JSON.stringify({current_name:name,profile_url:profile,previous_names:$('#playerAliases').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('#playerNotes').value.trim()})});$('#playerForm').reset();$('#playerDialog').close();await loadPlayers();}catch(err){alert('Could not save player: '+err.message)}};
 const saved=$('.dashboard-grid .panel:nth-child(2) .panelhead span');if(saved)saved.textContent='Private cloud database';const note=$('.prototype-note');if(note)note.textContent='Records are stored privately in Cloudflare D1 and sync across your devices.';
 const privacy=$('.privacy small');if(privacy)privacy.textContent='Confidential records and recommendations stay outside the public GitHub repository.';
}
window.addEventListener('highlife-authenticated',()=>{bind();loadPlayers();});
if(api.token){bind();loadPlayers();}
})();