(()=>{
const api=window.HighlifeAPI;if(!api)return;
const SOURCE='https://highliferoleplay.net/rules';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function addStyles(){if($('#dashboardUpdateStyles'))return;const s=document.createElement('style');s.id='dashboardUpdateStyles';s.textContent=`
#rulesUpdateCard{margin:16px 0 0;border:1px solid #35431d;background:linear-gradient(135deg,#111a13,#0d161e);border-radius:12px;padding:15px 17px;display:none}
#rulesUpdateCard.show{display:block}.ru-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.ru-title{display:flex;gap:10px;align-items:flex-start}.ru-dot{width:9px;height:9px;border-radius:50%;background:var(--lime);box-shadow:0 0 0 4px rgba(200,255,46,.07);margin-top:4px;flex:0 0 auto}.ru-title strong{display:block;font-size:12px;color:#dce6c0}.ru-title small{display:block;margin-top:4px;color:#788795;font-size:9px}.ru-actions{display:flex;gap:7px;align-items:center;flex:0 0 auto}.ru-actions a,.ru-actions button{border:0;background:transparent;color:#8797aa;font-size:9px;text-decoration:underline;text-underline-offset:3px;cursor:pointer;padding:2px}.ru-body{margin:12px 0 0 19px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.ru-block{border:1px solid #1d2c3b;background:#0a131c;border-radius:8px;padding:10px}.ru-block b{font-size:9px;text-transform:uppercase;letter-spacing:.07em;color:#758598}.ru-block.add b{color:#9fba62}.ru-block.remove b{color:#b8868d}.ru-block p{margin:7px 0 0;color:#a7b2bf;font-size:10px;line-height:1.45}.ru-none{color:#687789;font-style:italic}@media(max-width:700px){.ru-head{display:block}.ru-actions{margin:9px 0 0 19px}.ru-body{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function ensureCard(){let c=$('#rulesUpdateCard');if(c)return c;const welcome=$('#home .welcome');if(!welcome)return null;c=document.createElement('div');c.id='rulesUpdateCard';welcome.insertAdjacentElement('afterend',c);return c}
function fmtDate(v){if(!v)return'';const d=new Date(v.endsWith?.('Z')?v:v+'Z');return isNaN(d)?v:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
function render(data){const c=ensureCard();if(!c)return;const u=data?.update;if(!u){c.classList.remove('show');c.innerHTML='';return}const added=(u.added||[]).slice(0,3),removed=(u.removed||[]).slice(0,3);c.innerHTML=`<div class="ru-head"><div class="ru-title"><span class="ru-dot"></span><div><strong>Highlife rules were updated</strong><small>Detected ${esc(fmtDate(u.detected_at))}${u.source_updated_at?` · Official page: ${esc(u.source_updated_at)}`:''}</small></div></div><div class="ru-actions"><a href="${SOURCE}" target="_blank" rel="noreferrer">Open rules ↗</a><button id="rulesCheckNow">Check now</button></div></div><div class="ru-body"><div class="ru-block add"><b>Added / changed</b>${added.length?added.map(x=>`<p>${esc(x)}</p>`).join(''):'<p class="ru-none">No clean added line could be isolated — open the official rules to review the update.</p>'}</div><div class="ru-block remove"><b>Removed / replaced</b>${removed.length?removed.map(x=>`<p>${esc(x)}</p>`).join(''):'<p class="ru-none">Nothing clearly removed.</p>'}</div></div>`;c.classList.add('show');$('#rulesCheckNow').onclick=checkNow}
async function status(){try{const d=await api.request('/rules/status');render(d);const last=d.last_checked?new Date(d.last_checked+'Z').getTime():0;if(!last||Date.now()-last>6*60*60*1000)checkNow(true)}catch(e){console.warn('Rules status unavailable',e)}}
async function checkNow(silent=false){const b=$('#rulesCheckNow');if(b&&!silent){b.disabled=true;b.textContent='Checking…'}try{await api.request('/rules/check',{method:'POST'});const d=await api.request('/rules/status');render(d)}catch(e){if(!silent)alert('Could not check the rules page right now: '+e.message)}finally{const n=$('#rulesCheckNow');if(n){n.disabled=false;n.textContent='Check now'}}}
function bind(){addStyles();ensureCard();status()}
window.addEventListener('highlife-authenticated',bind);if(api.token)bind();
})();