(()=>{
const $=s=>document.querySelector(s),api=window.HighlifeAPI;if(!api)return;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const keyFor=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120);
let current=null, timer=null;
function ensureUI(){
 const box=$('#punishment .guidance'); if(!box||box.dataset.privateReady)return; box.dataset.privateReady='1'; box.classList.add('private-guidance-box');
 box.innerHTML=`<span>🔒</span><div class="private-guide-body"><div class="private-guide-head"><strong>Internal recommendation</strong><button class="guide-edit-btn" id="editGuideBtn" type="button">Edit private guidance</button></div><div id="guideContent"><p>Enter a rule above to load its private guidance.</p></div></div>`;
 $('#editGuideBtn').onclick=openEditor;
 const rule=$('#caseRule'); if(rule){rule.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(loadCurrent,250)});rule.addEventListener('change',loadCurrent)}
 if(!$('#guideDialog')){
  const d=document.createElement('dialog');d.id='guideDialog';d.className='guide-dialog';d.innerHTML=`<form method="dialog" id="guideForm"><div class="dialoghead"><div><p class="eyebrow">PRIVATE D1 DATA</p><h2>Penalty guidance</h2></div><button value="cancel" class="iconbtn">×</button></div><p class="guide-rule-name" id="guideRuleName"></p><label>Base recommendation<textarea id="guideBase" placeholder="e.g. Typical starting point, range, warning vs ban guidance..."></textarea></label><label>Repeat-offence guidance<textarea id="guideRepeat" placeholder="How repeat offences should normally escalate..."></textarea></label><label>Escalation notes<textarea id="guideEscalation" placeholder="When to escalate, senior-review triggers, exceptional circumstances..."></textarea></label><label>Considerations <small>One per line</small><textarea id="guideConsiderations" placeholder="Evidence quality\nIntent / severity\nTime since previous offence"></textarea></label><div class="guide-security">🔒 Saved only in your private Cloudflare D1 database.</div><div class="dialogactions"><button value="cancel" class="secondary">Cancel</button><button type="button" class="primary" id="saveGuideBtn">Save private guidance</button></div></form>`;document.body.appendChild(d);$('#saveGuideBtn').onclick=saveGuide;
 }
 loadCurrent();
}
async function loadCurrent(){const name=$('#caseRule')?.value.trim()||'';const content=$('#guideContent');if(!content)return;if(!name){current=null;content.innerHTML='<p>Enter a rule above to load its private guidance.</p>';return}const key=keyFor(name);content.innerHTML='<p class="guide-loading">Loading private guidance…</p>';try{const d=await api.request('/guidance/'+encodeURIComponent(key));current=d.guidance||null;render(name)}catch(e){current=null;content.innerHTML=`<p>Could not load guidance: ${esc(e.message)}</p>`}}
function render(name){const c=$('#guideContent');if(!c)return;if(!current){c.innerHTML=`<div class="guide-empty"><b>No guidance saved for ${esc(name)}</b><p>Add your internal base recommendation, repeat-offence guidance and escalation notes when you’re ready.</p></div>`;return}let considerations=[];try{considerations=JSON.parse(current.considerations||'[]')}catch{}
c.innerHTML=`<div class="guide-section"><small>BASE RECOMMENDATION</small><p>${esc(current.base_guidance||'No base recommendation saved.')}</p></div><div class="guide-section"><small>REPEAT OFFENCE</small><p>${esc(current.repeat_guidance||'No repeat guidance saved.')}</p></div><div class="guide-section"><small>ESCALATION</small><p>${esc(current.escalation_notes||'No escalation notes saved.')}</p></div>${considerations.length?`<div class="guide-section"><small>CONSIDER</small><ul>${considerations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div class="guide-updated">Private guidance updated ${current.updated_at?new Date(current.updated_at+'Z').toLocaleString('en-GB'):''}</div>`}
function openEditor(){const name=$('#caseRule')?.value.trim()||'';if(!name){alert('Enter or select a rule first.');$('#caseRule')?.focus();return}$('#guideRuleName').textContent=name;$('#guideBase').value=current?.base_guidance||'';$('#guideRepeat').value=current?.repeat_guidance||'';$('#guideEscalation').value=current?.escalation_notes||'';let cs=[];try{cs=JSON.parse(current?.considerations||'[]')}catch{}$('#guideConsiderations').value=cs.join('\n');$('#guideDialog').showModal()}
async function saveGuide(){const name=$('#caseRule')?.value.trim()||'';if(!name)return;const btn=$('#saveGuideBtn');btn.disabled=true;btn.textContent='Saving…';try{const body={rule_name:name,base_guidance:$('#guideBase').value.trim(),repeat_guidance:$('#guideRepeat').value.trim(),escalation_notes:$('#guideEscalation').value.trim(),considerations:$('#guideConsiderations').value.split('\n').map(x=>x.trim()).filter(Boolean)};const d=await api.request('/guidance/'+encodeURIComponent(keyFor(name)),{method:'PUT',body:JSON.stringify(body)});current=d.guidance;$('#guideDialog').close();render(name)}catch(e){alert('Could not save private guidance: '+e.message)}finally{btn.disabled=false;btn.textContent='Save private guidance'}}
window.HighlifePrivateGuidance={load:loadCurrent};
window.addEventListener('highlife-authenticated',ensureUI);if(api.token)ensureUI();
})();