(()=>{
const $=s=>document.querySelector(s);
const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9\s/-]/g,' ').replace(/\s+/g,' ').trim();
const has=(q,...xs)=>xs.some(x=>q.includes(x));
const matchers=[
 {id:'DEF-17',label:'Combat Logging',why:'The description suggests someone disconnected or left to avoid/finish an active situation.',score:q=>(has(q,'disconnect','disconnected','left the server','leave the server','logged out','combat log')?8:0)+(has(q,'arrest','police','chase','gunfight','fight','custody','danger','downed')?4:0)},
 {id:'IG-21',label:'10-minute disconnect rule',why:'Highlife also has a specific post-situation period before someone may leave the server.',score:q=>(has(q,'disconnect','disconnected','left the server','leave server','logged out')?6:0)+(has(q,'after','ended','finished','concluded','10 minute','ten minute')?4:0)},
 {id:'DEF-18',label:'Metagaming',why:'The description suggests out-of-character information may have affected in-character actions.',score:q=>(has(q,'discord','stream','twitch','ooc','out of character','outside the game','dm','message','chat')?7:0)+(has(q,'knew','knowledge','found out','information','location','told','watched')?4:0)},
 {id:'IG-14',label:'Out-of-game communications',why:'The situation appears to involve communications happening outside the game.',score:q=>has(q,'discord','out of game','outside game','dm','voice call','third party comm','ooc comm')?8:0},
 {id:'DEF-12',label:'RDM / Random Deathmatch',why:'The description suggests an attack or killing with little/no initiation or roleplay reason.',score:q=>(has(q,'shot','shoot','killed','kill','attacked','stabbed','opened fire')?6:0)+(has(q,'random','no reason','without reason','no initiation','without initiation','did nothing')?5:0)},
 {id:'DEF-14',label:'VDM / Vehicle Deathmatch',why:'A vehicle appears to have been used as a weapon without clear roleplay justification.',score:q=>(has(q,'ran over','run over','rammed','ramming','hit with car','vehicle as weapon','drove into')?9:0)+(has(q,'car','vehicle','truck','bike')&&has(q,'killed','downed','hit','attack')?3:0)},
 {id:'DEF-6',label:'Fear RP',why:'The description involves a credible threat where believable fear/self-preservation may be relevant.',score:q=>(has(q,'gunpoint','gun to','weapon pointed','held at gunpoint','hostage')?7:0)+(has(q,'ignored','laughed','walked away','pulled gun','fight back')?3:0)},
 {id:'IG-5',label:'Drawing a gun while already at gunpoint',why:'The situation specifically sounds like someone drew a weapon after already being held at gunpoint.',score:q=>(has(q,'gunpoint','gun pointed','held at gunpoint')?6:0)+(has(q,'pulled gun','drew gun','took out gun','weapon out','pulled a weapon')?7:0)},
 {id:'DEF-7',label:'NVL / Not Valuing Life',why:'The behaviour described may show disregard for the character’s life or immediate danger.',score:q=>(has(q,'nvl','not valuing life','reckless','no value for life')?9:0)+(has(q,'gunpoint','hostage','surrounded','outnumbered','danger')&&has(q,'ignored','charged','attacked','ran at','fight')?4:0)},
 {id:'DEF-3',label:'Powergaming',why:'The situation may involve forcing or using mechanics/outcomes that do not actually exist.',score:q=>(has(q,'powergame','powergaming','forced action','force action','impossible','mechanic does not exist','made me')?8:0)},
 {id:'DEF-10',label:'Fail RP',why:'The behaviour described may be broadly unrealistic or make little sense in a believable situation.',score:q=>(has(q,'failrp','fail rp','unrealistic','not realistic','makes no sense')?8:0)},
 {id:'DEF-8',label:'Lootboxing',why:'The description suggests indiscriminate looting or taking items without a sensible RP reason.',score:q=>(has(q,'looted everything','took everything','emptied pockets','lootboxed','loot boxing')?9:0)+(has(q,'loot','robbed items','inventory')?2:0)},
 {id:'IG-7',label:'Looting while uninvolved',why:'The person looting may not have been part of the original situation.',score:q=>(has(q,'loot','looted','took items')?5:0)+(has(q,'not involved','uninvolved','wasn\'t involved','random person','walked up')?6:0)},
 {id:'IG-16',label:'Remaining around a downed player',why:'The description suggests someone stayed/camped around a person they had downed.',score:q=>(has(q,'downed','killed','shot down')?4:0)+(has(q,'stayed','camped','waited','hung around','body')?5:0)},
 {id:'IG-19',label:'Changing clothes after crime/police involvement',why:'The description suggests clothing was changed too soon after criminal action or a police chase.',score:q=>(has(q,'changed clothes','change clothes','changed outfit','change outfit','clothing')?7:0)+(has(q,'chase','police','crime','criminal','after')?5:0)},
 {id:'IG-20',label:'Storing/retrieving a vehicle too soon',why:'The description suggests a vehicle was stored or retrieved shortly after a chase/criminal situation.',score:q=>(has(q,'stored vehicle','stored car','put car away','garage','retrieved vehicle','retrieved car','insurance')?7:0)+(has(q,'chase','police','crime','after')?4:0)},
 {id:'IG-22',label:'Fast travel / teleport during a situation',why:'The description suggests teleport/fast travel/property entry was used during an active situation.',score:q=>(has(q,'fast travel','teleport','teleported','property teleport','cayo travel')?9:0)},
 {id:'IG-24',label:'Repairing during a police pursuit',why:'The description suggests a vehicle was repaired during an active police pursuit/situation.',score:q=>(has(q,'repair','repaired','fix car','fixed car','mechanic repair')?5:0)+(has(q,'chase','pursuit','police')?6:0)},
 {id:'IG-25',label:'Outside interference in a police pursuit',why:'The description suggests outside players interfered with a police chase via ramming, ambush or added occupants.',score:q=>(has(q,'chase','pursuit')?4:0)+(has(q,'ram police','rammed police','ambush','outside help','joined chase','extra people','added occupants')?7:0)},
 {id:'IG-26',label:'Third-party interference',why:'The situation sounds like someone/group inserted themselves into a police or group conflict they were not originally part of.',score:q=>(has(q,'not involved','wasn\'t involved','third party','another group','inserted themselves','joined in')?6:0)+(has(q,'police situation','altercation','fight','shootout','conflict')?4:0)},
 {id:'IG-12',label:'Interfering with robbery/hostage situation',why:'The description suggests an uninvolved person/group interfered with an active robbery or hostage situation.',score:q=>(has(q,'robbery','hostage')?4:0)+(has(q,'interfered','joined','outside help','helped them','not involved','third party')?6:0)},
 {id:'ROB-3',label:'House / Store / ATM robbery limit',why:'A house/store/ATM robbery is mentioned, so the party/vehicle limit may apply.',score:q=>(has(q,'house robbery','store robbery','atm robbery','robbed a store','robbed atm')?8:0)+(has(q,'too many people','party limit','vehicles')?2:0)},
 {id:'ROB-4',label:'Commercial / Container robbery limit',why:'A commercial/container robbery is mentioned, so the relevant party/vehicle limit may apply.',score:q=>has(q,'commercial robbery','container robbery')?9:0},
 {id:'ROB-5',label:'Bank / Vangelico robbery limit',why:'A bank or Vangelico robbery is mentioned, so the relevant party/vehicle limit may apply.',score:q=>has(q,'bank robbery','vangelico')?9:0},
 {id:'ROB-6',label:'Humane Labs robbery limit',why:'Humane Labs is mentioned, so its specific party/vehicle limit may apply.',score:q=>has(q,'humane labs','humane lab')?10:0},
 {id:'ROB-7',label:'Union Depository robbery limit',why:'Union Depository is mentioned, so its specific party/vehicle limit may apply.',score:q=>has(q,'union depository','union depo')?10:0},
 {id:'HOLD-1',label:'Killing a compliant robbery victim',why:'The description suggests a compliant person may have been killed during a robbery.',score:q=>(has(q,'robbed','robbery','held up')?4:0)+(has(q,'complied','compliant','did everything','cooperated')?4:0)+(has(q,'killed','shot','executed')?5:0)},
 {id:'HOLD-2',label:'Forcing bank withdrawal/transfer',why:'The description suggests someone was forced to withdraw or transfer money from their bank.',score:q=>(has(q,'forced','made them')?3:0)+(has(q,'withdraw','bank transfer','transfer money','bank money')?7:0)},
 {id:'HOLD-6',label:'Holding up Police / EMS',why:'Police/EMS appear to have been targeted, so the online-count/equipment restrictions may apply.',score:q=>(has(q,'robbed police','robbed cop','held up police','held up cop','robbed ems','held up ems','stole police equipment','stole ems equipment')?9:0)},
 {id:'HOLD-7',label:'Holding up a player — police-online requirement',why:'A player hold-up/robbery is described, so the police-online requirement may be relevant.',score:q=>(has(q,'held up player','robbed player','robbed someone','mugged')?6:0)+(has(q,'police online','cops online','no police','officers online')?3:0)},
 {id:'HOST-1',label:'Friend used as hostage',why:'The description suggests a friend/associate may have been used as a hostage.',score:q=>(has(q,'hostage')?4:0)+(has(q,'friend','mate','group member','their own')?5:0)},
 {id:'HOST-2',label:'Money demanded for hostage',why:'The situation appears to involve demanding money in exchange for a hostage.',score:q=>(has(q,'hostage')?4:0)+(has(q,'ransom','demanded money','money for','pay for')?6:0)},
 {id:'HOST-5',label:'Hostage time limit',why:'The description mentions how long a hostage was held, so the hostage time cap may apply.',score:q=>(has(q,'hostage')?4:0)+(has(q,'30 minute','thirty minute','15 minute','fifteen minute','held for','hour')?5:0)},
 {id:'HOST-8',label:'Unrealistic / volunteered hostage',why:'The description suggests the hostage volunteered, was recruited, or received an incentive.',score:q=>(has(q,'hostage')?4:0)+(has(q,'volunteer','volunteered','asked to be','paid to be','agreed to be','fake hostage')?6:0)},
 {id:'HOST-9',label:'Hostage at government facility',why:'The hostage appears to have been taken/held at a hospital, police station or prison.',score:q=>(has(q,'hostage')?4:0)+(has(q,'hospital','pillbox','police station','pd','prison','government facility')?5:0)},
 {id:'IG-27',label:'Calling a service to rob/kidnap them',why:'The situation suggests a service was deliberately called in order to rob or kidnap the worker.',score:q=>(has(q,'called','requested','phoned')?3:0)+(has(q,'mechanic','ems','taxi','service')?3:0)+(has(q,'rob','kidnap','held up')?5:0)},
 {id:'IG-28',label:'Reckless driving / valuing life',why:'The driving described may recklessly endanger the character without a genuine purpose.',score:q=>(has(q,'reckless driving','drove off cliff','huge jump','dangerous driving','rammed through','full speed into')?8:0)},
 {id:'IG-32',label:'Character swapping into a known situation',why:'The description suggests someone switched characters to join a situation known from another character.',score:q=>(has(q,'switched character','changed character','other character','alt character')?5:0)+(has(q,'joined','came back','knew about','same situation')?5:0)},
 {id:'SR-3',label:'Aim-assisting software',why:'The description suggests use of aim assistance or third-party aiming software.',score:q=>has(q,'aimbot','aim assist','aim assisting','soft aim')?10:0},
 {id:'SR-4',label:'Unfair game modification / external crosshair',why:'The description suggests a modification or external crosshair that could provide an advantage.',score:q=>has(q,'crosshair','external crosshair','graphics mod','audio mod','visual mod','game modification')?8:0},
 {id:'SR-5',label:'VPN / proxy / cloud gaming',why:'The description mentions a prohibited connection method.',score:q=>has(q,'vpn','proxy','cloud gaming','geforce now')?10:0},
 {id:'SR-13',label:'Exploit / scripting / bug abuse',why:'The situation appears to involve exploiting, scripting or intentionally abusing a bug.',score:q=>has(q,'exploit','bug abuse','abused bug','script','scripting','dupe','duplicated items','glitch abuse')?10:0},
 {id:'STR-2',label:'Streaming staff channels',why:'The description suggests private/sensitive staff channels were shown on stream.',score:q=>(has(q,'stream','streamed','twitch','live')?4:0)+(has(q,'staff channel','staff chat','mod channel','private staff')?7:0)}
];
function rank(text){const q=norm(text);if(!q)return[];return matchers.map(m=>({...m,score:m.score(q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,7)}
function render(text){const q=String(text||'').trim(),box=$('#ruleResults');if(!q){box.innerHTML='<div class="empty">Describe what happened first.</div>';return}const hits=rank(q);if(!hits.length){box.innerHTML='<div class="empty">I could not confidently match that description. Try including the key action, who was involved, and what happened before/after it.</div>';return}const best=hits[0].score;box.innerHTML=`<div class="situation-summary"><b>${hits.length} possible rule${hits.length===1?'':'s'} found</b><small>These are leads for staff review, not an automatic ruling.</small></div>`+hits.map((h,i)=>`<button class="result situation-result" data-situation-rule="${h.id}"><span class="situation-rank">${i===0?'Most likely':h.score>=best-2?'Also likely':'Worth checking'}</span><b>${h.id} · ${h.label}</b><small>${h.why}</small></button>`).join('');box.querySelectorAll('[data-situation-rule]').forEach(b=>b.onclick=()=>{const id=b.dataset.situationRule;const inp=$('#ruleQuery');inp.value=id;$('#ruleSearch').click();});try{const r=JSON.parse(localStorage.getItem('hl_recent')||'[]');r.unshift({text:q,type:'Situation search',at:Date.now()});localStorage.setItem('hl_recent',JSON.stringify(r.slice(0,8)))}catch{}}
function bind(){const btn=$('#situationSearch'),ta=$('#situationQuery');if(!btn||!ta)return;btn.onclick=()=>render(ta.value);ta.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();render(ta.value)}});const hint=document.createElement('small');hint.className='situation-hint';hint.textContent='Tip: include the key action, who was involved, and what happened immediately before/after. Ctrl/Cmd + Enter to search.';ta.insertAdjacentElement('afterend',hint)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();