(()=>{
const $=s=>document.querySelector(s),api=window.HighlifeAPI;if(!api)return;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedPlayer=null,selectedRules=[];
function nav(page){document.querySelector(`[data-page="${page}"]`)?.click()}
function ensure(){
 const header=document.querySelector('header');if(header&&!$('#globalSearch')){const wrap=document.createElement('div');wrap.className='global-search-wrap';wrap.innerHTML='<input id="globalSearch" placeholder="Search everything…" autocomplete="off"><div id="globalResults" class="global-results" hidden></div>';header.insertBefore(wrap,header.querySelector('.status'));$('#globalSearch').addEventListener('input',debounce(globalSearch,220));document.addEventListener('click',e=>{if(!wrap.contains(e.target))$('#globalResults').hidden=true})}
 const navEl=$('#nav');if(navEl&&!document.querySelector('[data-page="builder"]')){const b=document.createElement('button');b.className='nav';b.dataset.page='builder';b.innerHTML='✦ <span>Case Builder</span>';navEl.insertBefore(b,navEl.querySelector('[data-page="punishment"]'));b.onclick=()=>showBuilder()}
 if(!$('#builder')){const sec=document.createElement('section');sec.className='page';sec.id='builder';sec.innerHTML=`<div class="sectionintro"><div><p class="eyebrow">GUIDED CASE WORKFLOW</p><h2>Case Builder</h2><p>Player → incident → rules → history → decision → saved case.</p></div><button class="secondary" id="builderReset">New case</button></div><div class="builder-grid"><article class="panel"><h3>1. Player</h3><div class="searchline"><input id="builderPlayer" placeholder="Name or profile URL…"><button class="secondary" id="builderFind">Find</button></div><div id="builderPlayers" class="results compact"></div><h3 class="subhead">2. What happened?</h3><textarea id="builderIncident" placeholder="Describe the incident in normal language…"></textarea><button class="primary full" id="builderSuggest">Suggest relevant rules</button><div id="builderRules" class="builder-rules"></div></article><article class="panel"><h3>3. Case decision</h3><div id="builderContext" class="empty compact">Choose a saved player and at least one rule.</div><label>Case / ticket link<input id="builderTicket" type="url" placeholder="Optional internal link…"></label><label>Evidence link(s)<textarea id="builderEvidence" placeholder="One per line"></textarea></label><div class="two-col"><label>Ban start<input id="builderStart" type="date"></label><label>Ban end<input id="builderEnd" type="date"></label></div><div class="builder-actions"><button class="secondary" id="builderCopy" type="button">Copy summary</button><button class="primary" id="builderSave">Save case</button></div></article></div>`;document.querySelector('main').appendChild(sec);$('#builderReset').onclick=resetBuilder;$('#builderFind').onclick=findPlayers;$('#builderPlayer').oninput=debounce(findPlayers,220);$('#builderSuggest').onclick=suggestRules;$('#builderCopy').onclick=copyBuilderSummary;$('#builderSave').onclick=saveBuilder}
 const home=$('#home .dashboard-grid');if(home&&!$('#backupPanel')){const p=document.createElement('article');p.className='panel';p.id='backupPanel';p.innerHTML='<div class="panelhead"><h3>Private data backup</h3></div><p class="mutedline">Export your private staff records and guidance as JSON.</p><button class="rowbtn" id="backupBtn">↓ Download backup</button>';home.appendChild(p);$('#backupBtn').onclick=backup}
 const rules=$('#rules');if(rules&&!$('#rulesHistoryPanel')){const p=document.createElement('article');p.className='panel rules-history-panel';p.id='rulesHistoryPanel';p.innerHTML='<div class="panelhead"><h3>Rules change history</h3><button class="textbtn" id="refreshRuleHistory">Refresh</button></div><div id="rulesHistoryList" class="empty compact">Loading detected changes…</div>';rules.appendChild(p);$('#refreshRuleHistory').onclick=loadRuleHistory;loadRuleHistory()}
 const clear=$('#clearRecent');if(clear){clear.textContent='Refresh';clear.onclick=loadActivity}
 loadActivity();watchSavedCases();
}
function showBuilder(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#builder').classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelector('[data-page="builder"]')?.classList.add('active');$('#pageTitle').textContent='Case Builder'}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function globalSearch(){const q=$('#globalSearch').value.trim(),box=$('#globalResults');if(q.length<2){box.hidden=true;return}try{const d=await api.request('/search?q='+encodeURIComponent(q));const ruleMatches=(window.HighlifeRules?.search?.(q)||[]).slice(0,5).map(x=>({type:'Rule',title:`${x.id} · ${x.title}`,sub:x.summary,page:'rules',query:x.title}));const all=[...ruleMatches,...(d.players||[]).map(x=>({type:'Player',title:x.current_name,sub:x.profile_url,page:'players'})),...(d.cases||[]).map(x=>({type:'Case',title:x.rule_name,sub:x.current_name+' · '+(x.incident_notes||''),page:'players'})),...(d.appeals||[]).map(x=>({type:'Appeal',title:x.current_name,sub:x.outcome+' · '+(x.notes||''),page:'appeals'}))];box.innerHTML=all.length?all.slice(0,14).map((x,i)=>`<button data-global-index="${i}"><small>${x.type}</small><b>${esc(x.title)}</b><span>${esc(x.sub).slice(0,110)}</span></button>`).join(''):'<div class="empty compact">No matching rules or private records.</div>';box.hidden=false;box.querySelectorAll('[data-global-index]').forEach(b=>b.onclick=()=>{const x=all[Number(b.dataset.globalIndex)];nav(x.page);if(x.type==='Rule'&&$('#ruleQuery')){$('#ruleQuery').value=x.query||q;$('#ruleSearch')?.click()}box.hidden=true})}catch(e){box.innerHTML=`<div class="empty compact">${esc(e.message)}</div>`;box.hidden=false}}
async function findPlayers(){const q=$('#builderPlayer').value.trim();try{const d=await api.request('/players'+(q?'?q='+encodeURIComponent(q):''));$('#builderPlayers').innerHTML=(d.players||[]).slice(0,6).map(p=>`<button class="builder-player" data-id="${p.id}"><b>${esc(p.current_name)}</b><small>${Number(p.case_count||0)} previous case(s)</small></button>`).join('')||'<div class="empty compact">No saved player found.</div>';$('#builderPlayers').querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{selectedPlayer=await api.request('/players/'+b.dataset.id);$('#builderPlayer').value=selectedPlayer.player.current_name;renderContext()})}catch(e){$('#builderPlayers').innerHTML=`<div class="empty compact">${esc(e.message)}</div>`}}
function suggestRules(){const text=$('#builderIncident').value.trim();if(!text)return;const rows=window.HighlifeRules?.search?window.HighlifeRules.search(text):[];selectedRules=[];$('#builderRules').innerHTML=(rows||[]).slice(0,8).map(r=>`<label class="builder-rule"><input type="checkbox" value="${esc(r.id)}"><span><b>${esc(r.id)} · ${esc(r.title)}</b><small>${esc(r.summary)}</small></span></label>`).join('')||'<div class="empty compact">No obvious rule match. Use Rule Finder to search manually.</div>';$('#builderRules').querySelectorAll('input').forEach(i=>i.onchange=()=>{selectedRules=[...$('#builderRules').querySelectorAll('input:checked')].map(x=>{const r=(rows||[]).find(y=>y.id===x.value);return r?`${r.id} · ${r.title}`:x.value});renderContext()})}
function renderContext(){const box=$('#builderContext');if(!selectedPlayer||!selectedRules.length){box.className='empty compact';box.textContent='Choose a saved player and at least one rule.';return}const cases=selectedPlayer.cases||[];box.className='builder-context';box.innerHTML=`<b>${esc(selectedPlayer.player.current_name)}</b><small>${cases.length} saved punishment(s)</small><div class="builder-rule-chips">${selectedRules.map(r=>`<span>${esc(r)}</span>`).join('')}</div>${cases.length?`<div class="builder-priors"><small>Recent history</small>${cases.slice(0,4).map(c=>`<div>${esc((c.rules||[c.rule_name]).join(', '))} <span>${c.duration_days||0}d</span></div>`).join('')}</div>`:''}`}
function builderSummary(){if(!selectedPlayer||!selectedRules.length)return'';const p=selectedPlayer.player,cases=selectedPlayer.cases||[],start=$('#builderStart').value||'—',end=$('#builderEnd').value||'—',duration=$('#builderStart').value&&$('#builderEnd').value?Math.max(0,Math.round((new Date($('#builderEnd').value)-new Date($('#builderStart').value))/86400000))+' days':'—';const priors=cases.length?cases.slice(0,5).map(c=>`- ${(c.rules||[c.rule_name]).join(', ')} | ${c.duration_days||0} days | ${c.ban_start||'—'} → ${c.ban_end||'—'}`).join('\n'):'- None saved';return `Player: ${p.current_name}\nProfile: ${p.profile_url}\nRules: ${selectedRules.join(', ')}\n\nIncident:\n${$('#builderIncident').value.trim()||'—'}\n\nPunishment:\n${start} → ${end} (${duration})\n\nPrior history:\n${priors}\n\nCase / Ticket: ${$('#builderTicket').value.trim()||'—'}\nEvidence:\n${$('#builderEvidence').value.trim()||'—'}`}
async function copyText(text,btn){if(!text)return alert('Choose a player and at least one rule first.');try{await navigator.clipboard.writeText(text);const old=btn?.textContent;if(btn){btn.textContent='Copied ✓';setTimeout(()=>btn.textContent=old,1200)}}catch{alert('Could not copy to clipboard.')}}
function copyBuilderSummary(){copyText(builderSummary(),$('#builderCopy'))}
async function saveBuilder(){if(!selectedPlayer)return alert('Choose a saved player first.');if(!selectedRules.length)return alert('Select at least one rule.');const body={player_id:selectedPlayer.player.id,rules:selectedRules,incident_notes:$('#builderIncident').value.trim(),ban_start:$('#builderStart').value||null,ban_end:$('#builderEnd').value||null,evidence_url:$('#builderEvidence').value.trim()||null,ticket_url:$('#builderTicket').value.trim()||null,prior_bans:[]};try{await api.request('/cases',{method:'POST',body:JSON.stringify(body)});alert('Case saved privately.');resetBuilder();loadActivity()}catch(e){alert('Could not save case: '+e.message)}}
function resetBuilder(){selectedPlayer=null;selectedRules=[];['#builderPlayer','#builderIncident','#builderTicket','#builderEvidence','#builderStart','#builderEnd'].forEach(s=>{if($(s))$(s).value=''});$('#builderPlayers').innerHTML='';$('#builderRules').innerHTML='';$('#builderContext').className='empty compact';$('#builderContext').textContent='Choose a saved player and at least one rule.'}
function savedCaseSummary(card){const player=$('#playerDetail h2')?.textContent?.trim()||'Unknown player',rule=card.querySelector('.casehead b')?.textContent?.trim()||'Unspecified',duration=card.querySelector('.casehead span')?.textContent?.trim()||'—',incident=card.querySelector('p')?.textContent?.trim()||'—',ban=[...card.querySelectorAll('.mutedline')].map(x=>x.textContent.trim()).join(' '),links=[...card.querySelectorAll('a')].map(a=>`${a.textContent.replace('↗','').trim()}: ${a.href}`).join('\n');return `Player: ${player}\nRule(s): ${rule}\nPunishment: ${duration}\n${ban}\n\nIncident:\n${incident}\n\n${links||'No saved links.'}`}
function injectSavedCaseButtons(){document.querySelectorAll('#playerDetail .casecard').forEach(card=>{if(card.querySelector('.copy-case-summary'))return;const b=document.createElement('button');b.className='textbtn copy-case-summary';b.type='button';b.textContent='Copy summary';b.onclick=()=>copyText(savedCaseSummary(card),b);const head=card.querySelector('.casehead');if(head)head.appendChild(b)})}
function watchSavedCases(){const detail=$('#playerDetail');if(!detail||detail.dataset.copyWatch)return;detail.dataset.copyWatch='1';new MutationObserver(injectSavedCaseButtons).observe(detail,{childList:true,subtree:true});injectSavedCaseButtons()}
async function loadActivity(){try{const d=await api.request('/activity');const box=$('#recentList');if(!box)return;box.innerHTML=(d.activity||[]).length?(d.activity||[]).map(a=>`<div class="activity-row"><span>${esc(a.icon||'•')}</span><div><b>${esc(a.title)}</b><small>${esc(a.detail||'')} · ${new Date(a.created_at+'Z').toLocaleString('en-GB')}</small></div></div>`).join(''):'<div class="empty compact">No recent private activity yet.</div>'}catch{}}
async function backup(){const btn=$('#backupBtn');btn.disabled=true;btn.textContent='Preparing…';try{const d=await api.request('/backup');const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`highlife-staff-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert('Backup failed: '+e.message)}finally{btn.disabled=false;btn.textContent='↓ Download backup'}}
async function loadRuleHistory(){try{const d=await api.request('/rules/history');const box=$('#rulesHistoryList');box.innerHTML=(d.updates||[]).length?d.updates.map(u=>`<div class="rule-history-row"><div><b>${u.source_updated_at?'Rules dated '+esc(u.source_updated_at):'Rules change detected'}</b><small>${new Date(u.detected_at+'Z').toLocaleString('en-GB')}</small></div><div>${(u.added||[]).slice(0,2).map(x=>`<p><strong>Added/changed:</strong> ${esc(x)}</p>`).join('')}${(u.removed||[]).slice(0,2).map(x=>`<p><strong>Removed/replaced:</strong> ${esc(x)}</p>`).join('')}</div></div>`).join(''):'<div class="empty compact">No rule changes have been detected since monitoring began.</div>'}catch(e){$('#rulesHistoryList').innerHTML=`<div class="empty compact">${esc(e.message)}</div>`}}
window.addEventListener('highlife-authenticated',ensure);setTimeout(ensure,900);
})();